require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - '.git/**/*'
    - "bin/**/*"
    - "db/**/*"
    - "public/**/*"
    - "tmp/**/*"
    - 'vendor/**/*'
Style/Documentation:
  Enabled: false